### ISSUE TITLE
Decorators for static methods

### ISSUE THREAD

**Issue by vpokutytskyi** [IhorAleksieienko/Dev274x-Python#2]
About decorators for static method:
there is the issue in code, actually class does not contain any static method. Static method should be declared using built-in decorator `staticmethod`

Correct snippet of code looks like

```
class original_fn:
    def __init__(self):
        self.val = 'val'

    def print_val(self, *args):  # instance method
        print("val  : ", self.val)

    @staticmethod
    @decor
    def print_args(*args):  # static method
        print("Subject  : ", *args)

    @decor
    def print_val_args(self, *args):  # instance method
        print("val  : ", self.val)
        print("Subject  : ", *args)
```

Without `@staticmethod` args parameter contains reference to object. It is important to remember what names `*args` and `**kwargs` are just the conventions for positional and keyword arguments names, it can be anything meaningful for developer

More about static methods in Python: https://realpython.com/instance-class-and-static-methods-demystified/

**Comment by IhorAleksieienko** [comment]
Thanks for your response. I've fixed that.
Maybe studying at midnight, not the best idea)
